### ISSUE TITLE
could not compile avx2 on macos

### ISSUE THREAD

**Issue by xiehuc** [WojciechMula/sse4-strstr#6]
In file included from src/all.h:18:
./avx2-strstr-v2.cpp:66:39: fatal error: argument to '__builtin_ia32_palignr256' must be a constant integer
            const __m256i substring = _mm256_alignr_epi8(next1, curr, i);
                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.0.0/include/avx2intrin.h:130:12: note:
      expanded from macro '_mm256_alignr_epi8'
  (__m256i)__builtin_ia32_palignr256((__v32qi)(__m256i)(a), \
           ^
1 error generated.

still, i tried a lot , could not fix this.

**Comment by WojciechMula** [comment]
There's clang on MacOS, is it?

**Comment by xiehuc** [comment]
yes and dont worry。if i really need it，i could install virtual machine。that is a not hurry problem。

and i think it is clang‘s problem

**Comment by WojciechMula** [comment]
@xiehuc Could you please check it?

**Comment by xiehuc** [comment]
yes, it works, thank you very much.
